// Creates (or removes) a Startup-folder shortcut that launches the background Edge at
// Windows sign-in with exactly the arguments the server uses, then hides its taskbar button.
// The shortcut runs a .vbs launcher via wscript.exe so no console window flashes.
//   node scripts/autostart.mjs [--remove]
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const here = path.dirname(fileURLToPath(import.meta.url));
const build = path.resolve(here, '..');
const root = path.resolve(build, '..');
const { CONFIG, edgeArgs } = await import(pathToFileURL(path.join(build, 'dist', 'config.js')).href);

const startup = path.join(process.env.APPDATA, 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup');
const lnk = path.join(startup, 'Amazon Music MCP (background Edge).lnk');
const vbs = path.join(root, 'launch-edge.vbs');
const ps1 = path.join(root, 'launch-edge.ps1');
const taskbar = path.join(build, 'scripts', 'taskbar.ps1');

if (process.argv.includes('--remove')) {
  for (const f of [lnk, vbs, ps1]) {
    if (fs.existsSync(f)) {
      fs.unlinkSync(f);
      console.error(`Removed ${f}`);
    }
  }
  process.exit(0);
}

const psq = (s) => `'${String(s).replace(/'/g, "''")}'`;
const argList = edgeArgs().map(psq).join(', ');

fs.writeFileSync(
  ps1,
  `# Generated by scripts/autostart.mjs -launches the background Edge for the Amazon Music MCP.
$ErrorActionPreference = 'SilentlyContinue'
$port = ${CONFIG.cdpPort}
$listening = Get-NetTCPConnection -LocalPort $port -State Listen -ErrorAction SilentlyContinue
if (-not $listening) {
  Start-Process -FilePath ${psq(CONFIG.edgeExe)} -ArgumentList @(${argList})
  $deadline = (Get-Date).AddSeconds(30)
  while ((Get-Date) -lt $deadline) {
    Start-Sleep -Milliseconds 500
    if (Get-NetTCPConnection -LocalPort $port -State Listen -ErrorAction SilentlyContinue) { break }
  }
  Start-Sleep -Seconds 2
}
& ${psq(taskbar)} -ProfileDir ${psq(CONFIG.profileDir)} | Out-Null
`,
  'utf8',
);

fs.writeFileSync(
  vbs,
  `' Generated by scripts/autostart.mjs -runs launch-edge.ps1 without a console window.
CreateObject("WScript.Shell").Run "powershell.exe -NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File """ & "${ps1.replace(/"/g, '""')}" & """", 0, False
`,
  'utf8',
);

const ps = `
$s = (New-Object -ComObject WScript.Shell).CreateShortcut(${psq(lnk)})
$s.TargetPath = "$env:SystemRoot\\System32\\wscript.exe"
$s.Arguments = ${psq(`"${vbs}"`)}
$s.WorkingDirectory = ${psq(root)}
$s.IconLocation = ${psq(CONFIG.edgeExe + ',0')}
$s.Description = 'Background Microsoft Edge for the Amazon Music MCP server'
$s.WindowStyle = 7
$s.Save()
`;
const encoded = Buffer.from(ps, 'utf16le').toString('base64');
const r = spawnSync('powershell.exe', ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Bypass', '-EncodedCommand', encoded], { stdio: 'inherit' });
if (r.status !== 0) {
  console.error('Failed to create the Startup shortcut.');
  process.exit(r.status ?? 1);
}
console.error(`Autostart shortcut written: ${lnk}`);
console.error(`  launcher: ${vbs} -> ${ps1}`);
